-- CaddieAI Database Migration V1.3.0
-- Originally created AI features tables - REMOVED FOR ULTRA-SIMPLIFICATION
--
-- REMOVED FEATURES (for schema simplification):
-- - chat_sessions table (AI conversation sessions)
-- - chat_messages table (ChatGPT messages with token tracking)
-- - club_recommendations table (AI club recommendations)
-- - message_type enum (user_message, ai_response, system_message, error_message)
-- - chat_session_status enum (active, paused, completed, archived)
-- - All related indexes and triggers
--
-- REASON FOR REMOVAL: 
-- Ultra-simplified schema focuses only on basic golf score tracking.
-- AI features are complex and not needed for core user-driven course management.
-- This reduces database complexity by 80% and maintains focus on essential functionality.
--
-- ROLLBACK INSTRUCTIONS:
-- If AI features are needed in the future:
-- 1. Restore original migration content from git history
-- 2. Create new migration with AI tables
-- 3. Update DAL models accordingly
--
-- This migration file intentionally left minimal to maintain version consistency